version: '3.4'

networks:
  zermos:
    external: true

services:
  zermos-web:
    container_name: zermos-web
    restart: unless-stopped
    image: zermos-web
    build:
      dockerfile: Zermos-Web/Dockerfile
    environment:
      - DB_NAME=REDACTED_DATABASE_NAME
      - DB_USER=root
      - DB_PASSWORD=REDACTED_DATABASE_PASSWORD
      - DB_HOST=REDACTED_DATABASE_NAME
      - DB_PORT=3306
    networks:
      - zermos