// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ZermosContext))]
    [Migration("20231105140714_notes_2.0")]
    partial class notes_20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Infrastructure.Entities.note", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NoteBookId")
                        .HasColumnType("longtext");

                    b.Property<string>("Omschrijving")
                        .HasColumnType("longtext");

                    b.Property<string>("Paragraphs")
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext");

                    b.Property<string>("Titel")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("lastEdit")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("Infrastructure.Entities.user", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cached_infowijs_calendar")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_infowijs_news")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_school_informationscreen")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_somtoday_absence")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_somtoday_grades")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_somtoday_homework")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_zermelo_schedule")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_huiswerk")
                        .HasColumnType("longtext");

                    b.Property<string>("infowijs_access_token")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("notities")
                        .HasColumnType("longtext");

                    b.Property<string>("school_id")
                        .HasColumnType("longtext");

                    b.Property<string>("settings")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_access_token")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_refresh_token")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_student_id")
                        .HasColumnType("longtext");

                    b.Property<string>("zermelo_access_token")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("zermelo_access_token_expires_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("email");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
