// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ZermosContext))]
    [Migration("20230808091549_zermelo_schedule_cache")]
    partial class zermelo_schedule_cache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Infrastructure.Entities.user", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("cached_infowijs_calendar")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_infowijs_news")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_school_informationscreen")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_somtoday_grades")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_somtoday_homework")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_zermelo_schedule")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_huiswerk")
                        .HasColumnType("longtext");

                    b.Property<string>("infowijs_access_token")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("school_id")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_access_token")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_refresh_token")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_student_id")
                        .HasColumnType("longtext");

                    b.Property<string>("theme")
                        .HasColumnType("longtext");

                    b.Property<string>("zermelo_access_token")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("zermelo_access_token_expires_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("email");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
