// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ZermosContext))]
    [Migration("20230624144718_removed_values")]
    partial class removed_values
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Infrastructure.Entities.user", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("infowijs_access_token")
                        .HasColumnType("text");

                    b.Property<string>("infowijs_session_token")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("school_id")
                        .HasColumnType("text");

                    b.Property<string>("school_naam_code")
                        .HasColumnType("text");

                    b.Property<string>("somtoday_access_token")
                        .HasColumnType("text");

                    b.Property<string>("somtoday_refresh_token")
                        .HasColumnType("text");

                    b.Property<string>("somtoday_student_id")
                        .HasColumnType("text");

                    b.Property<string>("somtoday_student_profile_picture")
                        .HasColumnType("text");

                    b.Property<string>("zermelo_access_token")
                        .HasColumnType("text");

                    b.HasKey("email");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
