// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ZermosContext))]
    partial class ZermosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Infrastructure.Entities.share", b =>
                {
                    b.Property<string>("key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("max_uses")
                        .HasColumnType("int");

                    b.Property<string>("page")
                        .HasColumnType("longtext");

                    b.Property<string>("value")
                        .HasColumnType("longtext");

                    b.HasKey("key");

                    b.ToTable("shares");
                });

            modelBuilder.Entity("Infrastructure.Entities.user", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cached_infowijs_news")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_somtoday_grades")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_somtoday_homework")
                        .HasColumnType("longtext");

                    b.Property<string>("cached_somtoday_leermiddelen")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_huiswerk")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_leermiddelen")
                        .HasColumnType("longtext");

                    b.Property<string>("infowijs_access_token")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("school_id")
                        .HasColumnType("longtext");

                    b.Property<string>("settings")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_access_token")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_refresh_token")
                        .HasColumnType("longtext");

                    b.Property<string>("somtoday_student_id")
                        .HasColumnType("longtext");

                    b.Property<string>("zermelo_access_token")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("zermelo_access_token_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("zermelo_school_abbr")
                        .HasColumnType("longtext");

                    b.Property<string>("zermelo_timestamps")
                        .HasColumnType("longtext");

                    b.HasKey("email");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
